//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.12 at 01:43:08 PM EET 
//


package com.example.lyst.tempo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.lyst.tempo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.lyst.tempo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ByNameDataSet }
     * 
     */
    public ByNameDataSet createByNameDataSet() {
        return new ByNameDataSet();
    }

    /**
     * Create an instance of {@link QueryByNameDataSet }
     * 
     */
    public QueryByNameDataSet createQueryByNameDataSet() {
        return new QueryByNameDataSet();
    }

    /**
     * Create an instance of {@link AddInteger }
     * 
     */
    public AddInteger createAddInteger() {
        return new AddInteger();
    }

    /**
     * Create an instance of {@link AddIntegerResponse }
     * 
     */
    public AddIntegerResponse createAddIntegerResponse() {
        return new AddIntegerResponse();
    }

    /**
     * Create an instance of {@link DivideInteger }
     * 
     */
    public DivideInteger createDivideInteger() {
        return new DivideInteger();
    }

    /**
     * Create an instance of {@link DivideIntegerResponse }
     * 
     */
    public DivideIntegerResponse createDivideIntegerResponse() {
        return new DivideIntegerResponse();
    }

    /**
     * Create an instance of {@link ByNameDataSet.ByName }
     * 
     */
    public ByNameDataSet.ByName createByNameDataSetByName() {
        return new ByNameDataSet.ByName();
    }

    /**
     * Create an instance of {@link QueryByNameDataSet.QueryByName }
     * 
     */
    public QueryByNameDataSet.QueryByName createQueryByNameDataSetQueryByName() {
        return new QueryByNameDataSet.QueryByName();
    }

}
